### ISSUE TITLE
proposal: postgresql as a part of a Docker setup

### ISSUE THREAD

**Issue by vblazenka** [krtech-digital/kerp#3]
Could we extend the Docker setup to have a database as a part of the setup? (maybe through docker-compose)

This would remove the extra dependency (Postgresql DB) that we need to have to run this project. This way we would just need to have Docker installed.

Pros:
- Docker image for running the database
- Docker will contain the config needed to set up admin user, port, etc..
- One less dependency on working machines

Cons:
- People will need to know how to connect to a running container if they decide to connect to the database via terminal

What do you think? Maybe I'm missing something. 😅

**Comment by kedmenecr** [comment]
Thanks for bringing it up!

We have disscused this internally and will provide the docker compose which will enable us to start all of the services.

Also we can provide a simple guide for connecting over docker/ rather teach about docker a little more (it will be covered in the talks on 15.6 - @Leeixi is having his presentatin)
